baseURL = "https://cv.fairviewlogic.io/"
title = "Mark Ryan"
locale = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 20

[module]
  [[module.imports]]
    path = "github.com/luizdepra/hugo-coder"

[services]
  [services.disqus]
  # shortname = ""

[markup]
  [markup.highlight]
  noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[params]
author = "Mark Ryan"
description = ""
keywords = "platform engineer,software engineer,kubernetes,docker,github"
info = [""]
avatarURL = "images/me.jpg"
dateFormat = "January 2, 2006"
colorScheme = "auto"
hideColorSchemeToggle = false
rtl = false
customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 1
url = "https://gitlab.com/mryan321/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/mark-ryan/"

[languages.en]
label = "English"

[[languages.en.menu.main]]
name = "Reading"
weight = 1
url = "reading/"

[[languages.en.menu.main]]
name = "Listening"
weight = 2
url = "listening/"

[[languages.en.menu.main]]
name = "CV"
weight = 3
url = "cv/"
